spring:
  application:
    name: demo
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: https://test/openid-connect/certs
    permit-get-path:
      - "/index.html"
      - "/swagger-ui"
      - "/swagger-ui/**"
    permit-post-path:
      - "test"
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
data:
  file-path: /config/schema-config/SCHEMA_TEMPLATE_SQL
  default-schema: adm
  schema-cmd: 'SET search_path TO "${tenant}"'